### ISSUE TITLE
NoSuchMethodError: java.nio.ByteBuffer.flip()

### ISSUE THREAD

**Issue by javeme** [tidb-incubator/hugegraph-on-tikv#13]
v0.12.1 init-store.sh error:
```java
Exception in thread "main" com.baidu.hugegraph.backend.BackendException: Failed to commit changes: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;(java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;)
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:393)
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:344)
	at com.baidu.hugegraph.backend.tx.GraphTransaction.addVertex(GraphTransaction.java:612)
	at com.baidu.hugegraph.auth.EntityManager.save(EntityManager.java:178)
	at com.baidu.hugegraph.auth.EntityManager.add(EntityManager.java:81)
	at com.baidu.hugegraph.auth.StandardAuthManager.createUser(StandardAuthManager.java:180)
	at com.baidu.hugegraph.auth.StandardAuthenticator.initAdminUser(StandardAuthenticator.java:70)
	at com.baidu.hugegraph.auth.StandardAuthenticator.initAdminUser(StandardAuthenticator.java:53)
	at com.baidu.hugegraph.auth.StandardAuthenticator.initAdminUserIfNeeded(StandardAuthenticator.java:185)
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:82)
2022-03-28 15:20:29 [main] [ERROR] c.b.h.b.Transaction - Failed to commit changes:
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at com.baidu.hugegraph.backend.serializer.BytesBuffer.require(BytesBuffer.java:173) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.serializer.BytesBuffer.writeBytes(BytesBuffer.java:294) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.serializer.BytesBuffer.writeString(BytesBuffer.java:331) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.serializer.BytesBuffer.writeProperty(BytesBuffer.java:583) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.serializer.BytesBuffer.writeProperty(BytesBuffer.java:530) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.serializer.BinarySerializer.formatProperties(BinarySerializer.java:206) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.serializer.BinarySerializer.writeVertex(BinarySerializer.java:393) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.prepareAdditions(GraphTransaction.java:341) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.prepareCommit(GraphTransaction.java:314) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.commit2Backend(IndexableTransaction.java:53) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commit(AbstractTransaction.java:238) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.commit(GraphTransaction.java:509) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:377) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:344) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.addVertex(GraphTransaction.java:612) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.auth.EntityManager.save(EntityManager.java:178) ~[hugegraph-core-0.12.0.jar:0.67.0.0]
	at com.baidu.hugegraph.auth.EntityManager.add(EntityManager.java:81) ~[hugegraph-core-0.12.0.jar:0.67.0.0]
	at com.baidu.hugegraph.auth.StandardAuthManager.createUser(StandardAuthManager.java:180) ~[hugegraph-core-0.12.0.jar:0.67.0.0]
	at com.baidu.hugegraph.auth.StandardAuthenticator.initAdminUser(StandardAuthenticator.java:70) ~[hugegraph-api-0.12.0.jar:0.67.0.0]
	at com.baidu.hugegraph.auth.StandardAuthenticator.initAdminUser(StandardAuthenticator.java:53) ~[hugegraph-api-0.12.0.jar:0.67.0.0]
	at com.baidu.hugegraph.auth.StandardAuthenticator.initAdminUserIfNeeded(StandardAuthenticator.java:185) ~[hugegraph-api-0.12.0.jar:0.67.0.0]
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:82) ~[hugegraph-dist-0.12.0.jar:?]
```

**Comment by javeme** [comment]
fixed by: https://github.com/hugegraph/hugegraph/pull/1653/commits/80ba06ebe50d4074fea1265fff92cc7e4b686378#diff-1eb8aabda35b33c3c13a0c11fb874c051dc56a9bc5371f85616b7a4dbc039c65R124
