### ISSUE TITLE
Continuous operations may not take effect: truncate server-info then add server-info

### ISSUE THREAD

**Issue by javeme** [tidb-incubator/hugegraph-on-tikv#14]
```java
2022-03-28 20:42:51 [gremlin-server-exec-2] [WARN] c.b.h.s.HugeSecurityManager - SecurityException: Not allowed to access system properties via Gremlin
2022-03-28 20:42:51 [gremlin-server-exec-2] [INFO] c.b.h.HugeGraph - Init server info [server-1-MASTER] for graph 'newhg'...
2022-03-28 20:42:51 [gremlin-server-exec-2] [INFO] c.b.h.t.ServerInfoManager - Init server info: HugeServerInfo(server-1){server_load=0, server_role=MASTER, id=server-1, label=~server, server_update_time=Mon Mar 28 20:42:51 CST 2022, server_max_load=10000}
2022-03-28 20:42:51 [gremlin-server-exec-2] [INFO] c.b.h.HugeGraph - Check olap property-key tables for graph 'newhg'
2022-03-28 20:42:51 [gremlin-server-exec-2] [WARN] c.b.h.s.HugeSecurityManager - SecurityException: Not allowed to access system properties via Gremlin
2022-03-28 20:42:51 [gremlin-server-exec-2] [INFO] c.b.h.HugeGraph - Restoring incomplete tasks for graph 'newhg'...
2022-03-28 20:42:51 [gremlin-server-exec-2] [INFO] c.b.h.HugeGraph - Graph 'newhg' has been truncated
2022-03-28 20:42:51 [task-scheduler-1] [WARN] c.b.h.t.ServerInfoManager - ServerInfo is missing: server-1
...
2022-03-28 21:05:28 [task-scheduler-1] [WARN] c.b.h.t.ServerInfoManager - ServerInfo is missing: server-1
2022-03-28 21:05:28 [task-scheduler-1] [ERROR] c.b.h.t.TaskManager - Exception occurred when schedule job
java.lang.NullPointerException: null
        at com.baidu.hugegraph.task.ServerInfoManager.heartbeat(ServerInfoManager.java:190) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.task.TaskManager.scheduleOrExecuteJobForGraph(TaskManager.java:302) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.task.TaskManager.scheduleOrExecuteJob(TaskManager.java:268) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
2022-03-28 21:05:29 [task-scheduler-1] [WARN] c.b.h.t.ServerInfoManager - ServerInfo is missing: server-1
2022-03-28 21:05:29 [task-scheduler-1] [ERROR] c.b.h.t.TaskManager - Exception occurred when schedule job
java.lang.NullPointerException: null
        at com.baidu.hugegraph.task.ServerInfoManager.heartbeat(ServerInfoManager.java:190) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.task.TaskManager.scheduleOrExecuteJobForGraph(TaskManager.java:302) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.task.TaskManager.scheduleOrExecuteJob(TaskManager.java:268) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]  

```

**Comment by javeme** [comment]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/9625821/160409774-a2715a77-ac4e-4e63-95c1-b6cfbc8bab0c.png">
https://github.com/tidb-incubator/hugegraph-on-tikv/blob/f6555aef016b7122b7df9eee7fe2e295f290bef3/src/main/java/com/baidu/hugegraph/backend/store/tikv/TikvStdSessions.java#L263
